export const CINDA_2025_RULESET = {
  id: "cinda-2025",
  label: "Règlement International Compétition 2025 · WNF / CINDA",
  sourceDocument: "Règles compétition Nanbudo.pdf",
  status: "architecture-ready",
  ambiguityPolicy: "Toute règle non encore structurée depuis le PDF doit être signalée comme non paramétrée au lieu d'être interprétée.",
  disciplines: {
    kata_individuel: { label: "Kata individuel", family: "kata", team: false, scoringModes: ["points", "flags"] },
    kata_equipe: { label: "Kata par équipe", family: "kata", team: true, scoringModes: ["points", "flags"] },
    randori: { label: "Randori", family: "randori", team: false, assaults: 7 },
    ju_randori: { label: "Ju Randori", family: "randori", team: false, assaults: 7 },
    ju_randori_equipe: { label: "Ju Randori par équipe", family: "randori", team: true, assaults: 7 },
    dantai_randori: { label: "Dantai Randori", family: "randori", team: true, future: true },
  },
  kata: {
    judges: ["Sushin", "Fukushin 1", "Fukushin 2", "Fukushin 3", "Fukushin 4"],
    scoring: { removeHighestAndLowest: true, result: "average_retained_scores" },
    katas: ["Nanbu Shodan", "Nanbu Nidan", "Nanbu Sandan", "Nanbu Yondan", "Nanbu Godan", "Ikkyoku", "Hyaku Hachi", "Seienchin", "Seipai", "Sampo Sho", "Shin Tajima", "Kaguya Hime"],
    noteValues: ["3.9", "4.0", "4.1", "4.2", "4.3", "4.4", "4.5", "4.6", "4.7", "4.8", "4.9"],
    childrenRules: { status: "to_be_structured_from_pdf" },
    specialCases: { status: "to_be_structured_from_pdf" },
  },
  randori: {
    officials: ["Sushin", "Fukushin", "Kanza", "Annonceur", "Chargé des notes"],
    defaultAssaults: 7,
    boutDurations: { status: "to_be_structured_from_pdf" },
    flagsDecision: { status: "to_be_structured_from_pdf" },
    drawsAndExtensions: { status: "to_be_structured_from_pdf" },
    withdrawalsAndInjuries: { status: "to_be_structured_from_pdf" },
    childrenRules: { status: "to_be_structured_from_pdf" },
  },
  penalties: {
    keikoku: { label: "Keikoku", consequence: { status: "to_be_structured_from_pdf" } },
    fujubun: { label: "Fujubun", consequence: { status: "to_be_structured_from_pdf" } },
    chui: { label: "Chui", consequence: { status: "to_be_structured_from_pdf" } },
    hansoku_chui: { label: "Hansoku Chui", consequence: { status: "to_be_structured_from_pdf" } },
    shikaku: { label: "Shikaku", consequence: { disqualification: true } },
  },
  categories: {
    minimumCompetitors: 3,
    regroupBelowMinimum: true,
    dimensions: ["sex", "age", "weight", "grade"],
    ageBands: [
      { id: "poussins", label: "Poussins", min: 0, max: 11, children: true },
      { id: "benjamins_minimes", label: "Benjamins / Minimes", min: 12, max: 14, children: true },
      { id: "cadets_juniors", label: "Cadets / Juniors", min: 15, max: 17, children: true },
      { id: "seniors", label: "Seniors", min: 18, max: 35, children: false },
      { id: "veterans", label: "Vétérans", min: 36, max: null, children: false },
    ],
    weightCategories: { status: "to_be_structured_from_pdf", appliesToFamilies: ["randori"] },
  },
};
