import { useEffect, useRef, useState } from "react";
import CompetitionDashboard from "./CompetitionDashboard";
import { BACKUP_KINDS, COMPETITIONS_STORAGE_KEY, buildBackup, cloneForStorage, createBackupFilename, downloadJsonFile, parseBackupFileContent } from "./backupUtils";

function CompetitionManager(){
 const importFileRef=useRef(null),importCompetitionRef=useRef(null),importAllRef=useRef(null);
 const [competitions,setCompetitions]=useState(()=>{try{const saved=localStorage.getItem(COMPETITIONS_STORAGE_KEY);return saved?JSON.parse(saved):[]}catch{return[]}});
 const [showForm,setShowForm]=useState(false);const [selectedCompetitionId,setSelectedCompetitionId]=useState(null);
 const [form,setForm]=useState({nom:"",date:"",lieu:"",type:"Coupe régionale",saison:"2026-2027",inscriptionsOuvertes:true});
 useEffect(()=>localStorage.setItem(COMPETITIONS_STORAGE_KEY,JSON.stringify(competitions)),[competitions]);
 function handleChange(e){const{name,value,type,checked}=e.target;setForm(c=>({...c,[name]:type==="checkbox"?checked:value}))}
 function createCompetition(e){e.preventDefault();if(!form.nom.trim()){alert("Indique le nom de la compétition.");return}const c={id:Date.now(),nom:form.nom.trim(),date:form.date,lieu:form.lieu.trim(),type:form.type,saison:form.saison,statut:"Préparation",inscriptionsOuvertes:Boolean(form.inscriptionsOuvertes),competitors:[],categories:[],pools:[]};setCompetitions(x=>[...x,c]);setForm({nom:"",date:"",lieu:"",type:"Coupe régionale",saison:"2026-2027",inscriptionsOuvertes:true});setShowForm(false)}
 function updateCompetition(c){setCompetitions(x=>x.map(v=>v.id===c.id?c:v))}
 function toggleRegistrations(id){setCompetitions(x=>x.map(c=>c.id===id?{...c,inscriptionsOuvertes:!c.inscriptionsOuvertes}:c))}
 function deleteCompetition(id){if(window.confirm("Supprimer cette compétition ?"))setCompetitions(x=>x.filter(c=>c.id!==id))}
 function exportCompetition(c){downloadJsonFile(buildBackup(BACKUP_KINDS.singleCompetition,{competition:cloneForStorage(c)}),createBackupFilename("competition",c))}
 function exportAllCompetitions(){if(!competitions.length){alert("Aucune compétition à sauvegarder.");return}downloadJsonFile(buildBackup(BACKUP_KINDS.allCompetitions,{competitions:cloneForStorage(competitions)}),createBackupFilename("toutes-les-competitions"))}
 function importCompetition(c){setCompetitions(current=>{const i=current.findIndex(x=>String(x.id)===String(c.id));if(i<0)return[...current,c];if(!window.confirm("Une compétition avec le même identifiant existe déjà. La remplacer ?"))return current;return current.map((x,n)=>n===i?c:x)})}
 function handleImportFile(e){const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const c=JSON.parse(r.result);if(!c?.id)throw new Error();importCompetition(c)}catch{alert("Import impossible : fichier invalide.")}finally{e.target.value=""}};r.readAsText(file)}
 function importCompetitionBackup(file){const r=new FileReader();r.onload=()=>{try{const b=parseBackupFileContent(String(r.result||""));if(b.kind!==BACKUP_KINDS.singleCompetition)throw new Error("Ce fichier n'est pas une sauvegarde d'une compétition seule.");importCompetition(cloneForStorage(b.data.competition))}catch(e){alert(`Import refusé : ${e.message}`)}};r.readAsText(file,"UTF-8")}
 function importAllCompetitionsBackup(file){const r=new FileReader();r.onload=()=>{try{const b=parseBackupFileContent(String(r.result||""));if(b.kind!==BACKUP_KINDS.allCompetitions)throw new Error("Ce fichier n'est pas une sauvegarde complète.");const list=cloneForStorage(b.data.competitions);if(window.confirm(`Restaurer ${list.length} compétition(s) ?`)){setCompetitions(list);setSelectedCompetitionId(null)}}catch(e){alert(`Restauration refusée : ${e.message}`)}};r.readAsText(file,"UTF-8")}
 function handleBackupFile(e,fn){const f=e.target.files?.[0];if(f)fn(f);e.target.value=""}
 const selected=competitions.find(c=>c.id===selectedCompetitionId);if(selected)return <CompetitionDashboard competition={selected} onBack={()=>setSelectedCompetitionId(null)} onUpdateCompetition={updateCompetition}/>;
 return <section className="competition-manager"><div className="manager-header"><div><p className="surtitle">BÊTA 0.2</p><h2>Gestion des compétitions</h2><p>Créez les compétitions et choisissez celles ouvertes aux inscriptions publiques.</p></div><div className="competitor-actions"><button className="primary" onClick={()=>setShowForm(v=>!v)}>{showForm?"Annuler":"+ Nouvelle compétition"}</button><input ref={importFileRef} type="file" accept="application/json,.json" onChange={handleImportFile} hidden/><button className="manage-button" type="button" onClick={()=>importFileRef.current?.click()}>Importer une compétition</button></div></div>
 <section className="backup-panel"><div><p className="surtitle">SAUVEGARDE</p><h3>Sauvegarde et restauration</h3></div><div className="backup-actions"><input ref={importCompetitionRef} type="file" accept="application/json,.json" onChange={e=>handleBackupFile(e,importCompetitionBackup)} hidden/><input ref={importAllRef} type="file" accept="application/json,.json" onChange={e=>handleBackupFile(e,importAllCompetitionsBackup)} hidden/><button className="manage-button" onClick={()=>importCompetitionRef.current?.click()}>Restaurer une compétition</button><button className="manage-button" onClick={exportAllCompetitions}>Sauvegarder toutes</button><button className="delete-button" onClick={()=>importAllRef.current?.click()}>Restaurer tout</button></div></section>
 {showForm&&<form className="competition-form" onSubmit={createCompetition}><h3>Nouvelle compétition</h3><label>Nom<input name="nom" value={form.nom} onChange={handleChange} placeholder="Ex. Coupe régionale Sud — Hiver" required/></label><div className="form-row"><label>Date<input name="date" type="date" value={form.date} onChange={handleChange}/></label><label>Lieu<input name="lieu" value={form.lieu} onChange={handleChange}/></label></div><div className="form-row"><label>Type<select name="type" value={form.type} onChange={handleChange}><option>Coupe régionale</option><option>Coupe de France</option><option>Open</option><option>Championnat</option><option>Autre</option></select></label><label>Saison<input name="saison" value={form.saison} onChange={handleChange}/></label></div><label><input type="checkbox" name="inscriptionsOuvertes" checked={form.inscriptionsOuvertes} onChange={handleChange}/> Ouvrir immédiatement les inscriptions publiques</label><button className="primary" type="submit">Créer la compétition</button></form>}
 {competitions.length===0?<div className="empty-state"><span className="empty-number">0</span><h3>Aucune compétition</h3></div>:<div className="managed-competitions">{competitions.map(c=><article className="managed-competition" key={c.id}><div className="competition-main"><span className="status">{c.inscriptionsOuvertes?"Inscriptions ouvertes":"Inscriptions fermées"}</span><h3>{c.nom}</h3><p>{c.type}{c.lieu?` · ${c.lieu}`:""}</p><p className="competition-date">{c.date||"Date à définir"} · Saison {c.saison}</p></div><div className="competition-stats"><div><strong>{c.competitors?.length||0}</strong><span>Compétiteurs</span></div><div><strong>{c.categories?.length||0}</strong><span>Catégories</span></div></div><div className="competition-actions"><button className="manage-button" onClick={()=>toggleRegistrations(c.id)}>{c.inscriptionsOuvertes?"Fermer inscriptions":"Ouvrir inscriptions"}</button><button className="manage-button" onClick={()=>exportCompetition(c)}>Sauvegarder</button><button className="manage-button" onClick={()=>setSelectedCompetitionId(c.id)}>Gérer</button><button className="delete-button" onClick={()=>deleteCompetition(c.id)}>Supprimer</button></div></article>)}</div>}
 <div className="beta-note"><strong>Mode bêta</strong><p>Les compétitions ouvertes apparaissent automatiquement dans le formulaire public d'inscription sur cet appareil.</p></div></section>
}
export default CompetitionManager;
