import { useState } from "react";

function MatchManager({ match, onSave }) {
  const [kataAka, setKataAka] = useState(match?.kataAka || ["", "", ""]);
  const [kataShiro, setKataShiro] = useState(match?.kataShiro || ["", "", ""]);
  const [combat, setCombat] = useState({ akaScore: match?.akaScore ?? 0, shiroScore: match?.shiroScore ?? 0, avertissementsAka: match?.avertissementsAka ?? 0, avertissementsShiro: match?.avertissementsShiro ?? 0, penalitesAka: match?.penalitesAkaCount ?? 0, penalitesShiro: match?.penalitesShiroCount ?? 0 });
  const isKata = match.discipline === "kata";
  const sum = (values) => values.reduce((total, value) => total + Number(value || 0), 0);
  const kataScoreAka = sum(kataAka);
  const kataScoreShiro = sum(kataShiro);
  const winner = isKata ? (kataScoreAka > kataScoreShiro ? "aka" : kataScoreShiro > kataScoreAka ? "shiro" : null) : (combat.akaScore - combat.penalitesAka > combat.shiroScore - combat.penalitesShiro ? "aka" : combat.shiroScore - combat.penalitesShiro > combat.akaScore - combat.penalitesAka ? "shiro" : null);
  function save() { onSave(isKata ? { kataAka, kataShiro, scoreAka: kataScoreAka, scoreShiro: kataScoreShiro, vainqueur: winner } : { ...combat, scoreAka: combat.akaScore - combat.penalitesAka, scoreShiro: combat.shiroScore - combat.penalitesShiro, vainqueur: winner }); }

  return <section className="match-manager"><div className="manager-header"><div><p className="surtitle">{isKata ? "KATA" : "COMBAT"}</p><h2>{isKata ? "Feuille officielle de notation Kata" : "Feuille officielle Combat"}</h2><p>{match.categoryName}</p></div></div><div className="match-score"><div><strong>🔴 AKA</strong><h2>{isKata ? kataScoreAka : combat.akaScore - combat.penalitesAka}</h2><p>{match.aka?.nom} {match.aka?.prenom}</p><p>{match.aka?.club || "Club non renseigné"}</p></div><div><strong>⚪ SHIRO</strong><h2>{isKata ? kataScoreShiro : combat.shiroScore - combat.penalitesShiro}</h2><p>{match.shiro?.nom} {match.shiro?.prenom}</p><p>{match.shiro?.club || "Club non renseigné"}</p></div></div>{isKata ? <div className="assauts"><h3>Notes Kata</h3>{[0, 1, 2].map((index) => <div className="juge" key={index}><span>Juge {index + 1}</span><input type="number" step="0.1" value={kataAka[index]} onChange={(event) => setKataAka(kataAka.map((value, itemIndex) => itemIndex === index ? event.target.value : value))} placeholder="AKA" /><input type="number" step="0.1" value={kataShiro[index]} onChange={(event) => setKataShiro(kataShiro.map((value, itemIndex) => itemIndex === index ? event.target.value : value))} placeholder="SHIRO" /></div>)}</div> : <div className="penalties"><h3>Score, avertissements et pénalités</h3><div className="penalties-grid">{[["aka", "AKA"], ["shiro", "SHIRO"]].map(([side, label]) => <div className="penalty-card" key={side}><h3>{label}</h3><label>Score<input type="number" value={combat[side === "aka" ? "akaScore" : "shiroScore"]} onChange={(event) => setCombat({ ...combat, [side === "aka" ? "akaScore" : "shiroScore"]: Number(event.target.value) })} /></label><label>Avertissements<input type="number" value={combat[side === "aka" ? "avertissementsAka" : "avertissementsShiro"]} onChange={(event) => setCombat({ ...combat, [side === "aka" ? "avertissementsAka" : "avertissementsShiro"]: Number(event.target.value) })} /></label><label>Pénalités<input type="number" value={combat[side === "aka" ? "penalitesAka" : "penalitesShiro"]} onChange={(event) => setCombat({ ...combat, [side === "aka" ? "penalitesAka" : "penalitesShiro"]: Number(event.target.value) })} /></label></div>)}</div></div>}<div className="match-result"><h3>Vainqueur</h3><p>{winner === "aka" ? `AKA · ${match.aka?.nom} ${match.aka?.prenom}` : winner === "shiro" ? `SHIRO · ${match.shiro?.nom} ${match.shiro?.prenom}` : "Égalité / à départager"}</p><button className="primary" onClick={save}>Valider le résultat</button></div></section>;
}
export default MatchManager;
